image: registry.sensetime.com/zoetrope/pytorch@sha256:fa23a6b9ed9b5d90f2ec9ea34e99987e8b44d8ae80acd2149df6fe5b97a4e488

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
    - linting
    - test

before_script:
  - echo $PATH
  - ls /workspace
  - gcc --version
  - python --version
  - pip --version
  - nvcc --version
  - cmake --version
  - python -c "import torch; print(torch.__version__)"
  - export http_proxy=http://172.16.1.135:3128/
  - export https_proxy=http://172.16.1.135:3128/
  - export HTTP_PROXY=http://172.16.1.135:3128/
  - export HTTPS_PROXY=http://172.16.1.135:3128/

linting:
  stage: linting
  script:
    - pre-commit install
    - pre-commit run --all-files --verbose
    - echo "Docstring coverage results:"
    - interrogate -vinmMI -f 40 xrmocap/
test:
  stage: test
  tags:
    - gpu
  script:
    - nvidia-smi
    - echo "Start building..."
    - echo "--- install xrprimer --- "
    - cd xrprimer
    - pip install conan
    - conan remote add xrlab http://conan.kestrel.sensetime.com/artifactory/api/conan/xrlab
    - cmake -S. -Bbuild && cmake --build build -j4
    - cd python && pip install -e .
    - python -c "import xrprimer; print(xrprimer.__version__)"
    - cd ../../
    - pip install -e .
    - echo "--- xrprimer installed --- "
    - echo "--- install mmhuman3d --- "
    - pip install git+https://github.com/open-mmlab/mmhuman3d.git
    - echo "--- mmhuman3d installed --- "
    - unset http_proxy
    - unset https_proxy
    - unset HTTP_PROXY
    - unset HTTPS_PROXY
    - sh script/download_test_data.sh
    - mkdir -p xrmocap/keypoints3d_estimation/lib
    - cd xrmocap/keypoints3d_estimation/lib
    - python setup.py build_ext --inplace
    - cd ../../../
    - echo "Start testing..."
    - coverage run --source xrmocap -m pytest -s test/
    - coverage report -m
